import json
import plotly.graph_objects as go
import streamlit as st

# Page configuration
st.set_page_config(
    page_title="Inflation Shield", layout="wide"
)

# Translations dictionary
I18N = {
    "en": {
        "title": "Inflation Shield",
        "subtitle": "Personal Inflation Calculator",
        "desc": "Calculate your personal inflation rate based on your actual daily expenses.",
        "settings": "Settings",
        "select_country": "Select Country:",
        "select_lang": "Select Language:",
        "expenses_header": "Your Monthly Expenses",
        "curr_expenses": "Current Monthly Expenses",
        "official_cpi": "Official Inflation (CPI)",
        "personal_cpi": "Personal Inflation",
        "vs_official": "vs Official",
        "chart_title": "Expense Growth Forecast",
        "your_rate": "With Personal Inflation",
        "off_rate": "With Official Inflation",
        "time_horizon": "Time Horizon",
        "monthly_expenses": "Monthly Expenses",
        "table_title": "Expense Breakdown",
        "col_category": "Category",
        "col_amount": "Amount",
        "col_share": "Share",
        "col_rate": "Category Inflation",
        "now": "Now",
        "year": "year",
        "years": "years",
        "inflation": "Inflation",
    },
    "de": {
        "title": "Inflation Shield",
        "subtitle": "Persönlicher Inflationsrechner",
        "desc": "Berechnen Sie Ihre persönliche Inflationsrate basierend auf Ihren tatsächlichen Ausgaben.",
        "settings": "Einstellungen",
        "select_country": "Land auswählen:",
        "select_lang": "Sprache auswählen:",
        "expenses_header": "Ihre monatlichen Ausgaben",
        "curr_expenses": "Aktuelle monatliche Ausgaben",
        "official_cpi": "Offizielle Inflation (VPI)",
        "personal_cpi": "Persönliche Inflation",
        "vs_official": "ggü. offizieller Rate",
        "chart_title": "Prognose der Ausgabenentwicklung",
        "your_rate": "Mit persönlicher Inflation",
        "off_rate": "Mit offizieller Inflation",
        "time_horizon": "Zeithorizont",
        "monthly_expenses": "Monatliche Ausgaben",
        "table_title": "Ausgabenstruktur",
        "col_category": "Kategorie",
        "col_amount": "Betrag",
        "col_share": "Anteil",
        "col_rate": "Kategorie-Inflation",
        "now": "Jetzt",
        "year": "Jahr",
        "years": "Jahre",
        "inflation": "Inflation",
    },
    "ja": {
        "title": "インフレ・シールド",
        "subtitle": "個人インフレ率計算ツール",
        "desc": "実際の日常の支出に基づいて、あなた個人のインフレ率を計算します。",
        "settings": "設定",
        "select_country": "国を選択:",
        "select_lang": "言語を選択:",
        "expenses_header": "毎月の支出",
        "curr_expenses": "現在の月間支出",
        "official_cpi": "公式インフレ率 (CPI)",
